title: My GitHub Pages Site
description: A clean, modern GitHub Pages template
baseurl: ""
url: "https://soar-fly.github.io"
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom variables
author:
  name: "soar-fly"
  email: "feiyang.chen.life@outlook.com"

home:
  featured_posts: 3
  hero_button_text: "Explore More"